version: "3"
services:
  xgboost_regressor:
    build: .
    volumes:
      - ./ml_vol:/opt/ml_vol
    ports:
      - 8080:8080
    working_dir: /opt/ModellingLogistic
    command: tail -f /dev/null # keep the container running
    
