#!/usr/bin/env Rscript

library(rjson)
library(data.table)
library(tidyr)

fname_test <- dir(path = "./../ml_vol/inputs/data/testing/binaryClassificationBaseMainInput/", pattern = "\\_test.csv$")
fname_testschema <- dir(path = "./../ml_vol/inputs/data_config/", pattern = "\\_schema.json$")
testdata <- fread(paste0("./../ml_vol/inputs/data/testing/binaryClassificationBaseMainInput/",fname_test))

tdataschema <- fromJSON(file = paste0("./../ml_vol/inputs/data_config/",fname_testschema))

# select the ID column into a variable and drop it from the test data. 
# the variable created will be bound to the predicted probabilities 

idfieldname <- tdataschema$inputDatasets$binaryClassificationBaseMainInput$idField


source("preprocessor.R")

output_vector <- preprocessing(fname_train=fname_test,fname_schema=fname_schema,genericdata=testdata,dataschema=tdataschema)[[2]]
resvar <- preprocessing(fname_train=fname_test,fname_schema=fname_schema,genericdata=testdata,dataschema=tdataschema)[[4]]
testdata_matrix <- preprocessing(fname_train=fname_test,fname_schema=fname_schema,genericdata=testdata,dataschema=tdataschema)[[1]]
test_data <- preprocessing(fname_train=fname_test,fname_schema=fname_schema,genericdata=testdata,dataschema=tdataschema)[[5]]

# load the trained model
xgb_logistic <- readRDS("./../ml_vol/model/artifacts/model.rds")

testing <- function()
{
  df <- testdata_matrix
  predictions <- predict(xgb_logistic, newdata = testdata_matrix , type = "response")
  # label encode the response variable
  #test_data[,c(eval(resvar))] <- as.numeric(factor(test_data[,c(eval(resvar))]))
  thepredictions <- cbind(test_data, predictions)
  testdata_preds <- thepredictions[,c(eval(idfieldname),eval(resvar),"predictions")]
  
  testpredictions <- tidyr::pivot_wider(testdata_preds,names_from=eval(resvar),values_from="predictions")
  # colname_first_category <- names(testpredictions)[2]
  # colname_second_category <- names(testpredictions)[3]
  #testpredictions <- setDT(testpredictions)[,c(eval(idfieldname),eval(colname_first_category))]
  # testpredictions_n <- setDT(testpredictions)[is.na(eval(colname_first_category)),
  #                                             eval(colname_first_category) := 
  #                                               1-eval(colname_second_category)][is.na(eval(colname_second_category)),
  #                                                                                eval(colname_second_category) := 1-eval(colname_first_category)]
  
  testpredictions_n <- setDT(testpredictions)[is.na(`1`),`1` := 1-`0`][is.na(`0`),`0` := 1-`1`]
  
  #print(testpredictions)
  write.csv(testpredictions_n,"./../ml_vol/outputs/testing_outputs/testpredictions.csv")

}

testing()
